### ISSUE TITLE
Wrong docs - missing install script

### ISSUE THREAD

**Issue by fatso83** [kevinSuttle/dotfiles#2]
In VundleVim/Vundle.vim#226 you refer to some lines in your install script. That script missing, which of course is fine in your own repo, but your docs also still refer to this non-existing file.

Btw, which commit would include those lines that you refer to?

**Comment by kevinSuttle** [comment]
https://github.com/kevinSuttle/dotfiles/blob/b184ae70b250ea7d913a6aadfd57814a6900a339/install.zsh#L22

**Comment by kevinSuttle** [comment]
Where do I mention this in my docs?
